debug: false
spring:
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template: false
#    enable-spring-el-compiler: true
  data:
    mongodb:
      database: test
      uri: mongodb+srv://chenmo:chenmoand@cluster0-jbhpo.mongodb.net/test?retryWrites=true&w=majority
server:
  compression:
    enabled: true