debug: false
spring:
  devtools:
    add-properties: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template: false
#    enable-spring-el-compiler: true
  data:
    mongodb:
      database: test
      uri: mongodb+srv://chenmo:chenmoand@cluster0-jbhpo.mongodb.net/test?retryWrites=true&w=majority
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    web: DEBUG