debug: false
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template: false
  data:
    mongodb:
      database: test
      uri: mongodb+srv://chenmo:chenmoand@cluster0-jbhpo.mongodb.net/test?retryWrites=true&w=majority
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true