spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template: false
  data:
    mongodb:
      uri: mongodb+srv://chenmo:www.brageast.com@cluster0-jbhpo.mongodb.net/test
