spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    check-template: false
  webflux:
    static-path-pattern: classpath:/static/**
#  data:
#    mongodb:
#      host: jd.brageast.com
